#!/usr/bin/python
import os
from subprocess import Popen
from os.path import expanduser
home = expanduser("~")

os.chdir(home)
os.system("rm -rf prepare")
os.system("mkdir prepare")
os.system("sudo apt-get -qq install software-properties-common python-software-properties")
os.system("sudo add-apt-repository -y ppa:named-data/ppa")
os.system("sudo apt-get -qq update")
os.system("sudo apt-get -qq install libboost1.55-all-dev libcrypto++-dev pkg-config libsqlite3-dev libssl-dev python-sphinx liblog4cxx10-dev libprotobuf-dev libprotoc-dev protobuf-compiler")
